apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  local:
    path: /mnt/data/stayledger/ai-assistant/stayledger-ai-assistant-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - stayledger
