apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stayledger-guest-documents
spec:
  storageClassName: local-storage-stayledger
  volumeName: stayledger-production-guest-documents-pv
  resources:
    requests:
      storage: 40Gi
