apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stayledger-ai-assistant
  namespace: argocd
spec:
  description: StayLedger AI Assistant GitOps project
  sourceRepos:
    - https://github.com/tuantruong379/stayledger-infra.git
  destinations:
    - namespace: stayledger-ai-assistant
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
