apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: hotel-assistant
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: hotel-assistant
    app.kubernetes.io/component: database
data:
  init-data.sh: |
    #!/bin/bash
    set -e
    if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
        GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DATABASE ${POSTGRES_DB} OWNER TO "${POSTGRES_NON_ROOT_USER}";
        GRANT USAGE, CREATE ON SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
        GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "${POSTGRES_NON_ROOT_USER}";
      EOSQL
    else
      echo "SETUP INFO: No Environment variables given!"
    fi

