apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: stayledger-ai-assistant
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: stayledger-ai-assistant
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: postgres-sc
  volumeName: postgres-pv
  volumeMode: Filesystem

