apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: hotel-assistant
    app.kubernetes.io/component: cache
spec:
  capacity:
    storage: 10Gi
  local:
    path: /mnt/hotel-assistant/redis
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-sc
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hkk8s-hub-master

