apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-assistant-rag-eval-worker
spec:
  template:
    spec:
      containers:
        - name: rag-eval-worker
          image: putin111/ai-hotel-assistant@sha256:fe966dffdb45dfa41b146134708108346d2ec37dec12ab5a4fe5638b294a4d94
