apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayledger-ai-assistant-admin-web
  namespace: stayledger-ai-assistant
spec:
  replicas: 1

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stayledger-ai-assistant-admin-web
  namespace: stayledger-ai-assistant
spec:
  minReplicas: 1
  maxReplicas: 2
