apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-ingress
  namespace: stayledger-ai-assistant
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: stayledger-ai-assistant-postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: stayledger-ai-assistant-postgres
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgres-backup
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: stayledger-ai-assistant-pgbouncer
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: stayledger-ai-assistant-postgres-exporter
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: stayledger-ai-assistant-metrics-aggregator
    ports:
    - protocol: TCP
      port: 5432
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 5432
