apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stayledger-ai-assistant-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=putin111/ai-hotel-assistant
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: release/1.2.0
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^[0-9a-f]{7,40}$
    argocd-image-updater.argoproj.io/api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/api.kustomize.image-name: putin111/ai-hotel-assistant
spec:
  project: stayledger-ai-assistant
  source:
    repoURL: https://github.com/tuantruong379/stayledger-infra.git
    targetRevision: release/ai-assistant-1.2.25
    path: stayledger-ai-assistant-api/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: stayledger-ai-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
