apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayledger-ai-assistant-rag-eval-worker
spec:
  template:
    spec:
      containers:
        - name: rag-eval-worker
          image: putin111/stayledger-ai-assistant-api@sha256:1febf1ad51c3e4bf2910d750dc752885f5046e7d243456c9d67edf6ee19c8844
