cat admin-hotel-assistant.tekcent.com
##
# API upstream
##
upstream admin_hotel_assistant_api_upstream {
    server 10.89.1.40:30081 max_fails=3 fail_timeout=10s;

    keepalive 256;
    keepalive_requests 1000;
    keepalive_timeout 60s;
}


server {
    listen 80;
    server_name admin-hotel-assistant.tekcent.com ;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name admin-hotel-assistant.tekcent.com ;

    ssl_certificate     /usr/local/share/ca-certificates/tekcent.com.crt;
    ssl_certificate_key /usr/local/share/ca-certificates/tekcent.com.key;

    client_max_body_size 16m;


    ##
    # ADMIN
    ##
    location / {
        proxy_pass http://admin_hotel_assistant_api_upstream;

        proxy_http_version 1.1;

        proxy_set_header Connection "";
        proxy_set_header Upgrade "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_connect_timeout 10s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        proxy_socket_keepalive on;
        proxy_request_buffering on;

        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 8 256k;
        proxy_busy_buffers_size 256k;
    }
}
