apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: stayledger-ai-assistant
  labels:
    app.kubernetes.io/name: stayledger-ai-assistant-admin-web
    app.kubernetes.io/part-of: stayledger-ai-assistant
automountServiceAccountToken: false
