apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayledger-ai-assistant-admin-web
  namespace: stayledger-ai-assistant
spec:
  template:
    spec:
      containers:
        - name: frontend
          command: ["./docker-entrypoint.sh"]
          args: []
