apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: stayledger-ai-assistant
  labels:
    app.kubernetes.io/name: stayledger-ai-assistant-redis
    app.kubernetes.io/part-of: stayledger-ai-assistant
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis-sc
  volumeName: redis-pv
  volumeMode: Filesystem

